### ISSUE TITLE
Changing user details returns a 500 error

### ISSUE THREAD

**Issue by OlekAleksander** [Jexactyl/Jexactyl#171]
### Current Behavior

When changing users details and pressing save it redirects to a 500 page and the details dont change.

### Expected Behavior

After pressing save the page should reload and save the details.

### Steps to Reproduce

Change details of an user.
See the error.

### Panel Version

3.5.0

### Wings Version

1.7.2

### Error Logs

```bash
#52 /var/www/jexactyl/vendor/laravel/framework/src/Illuminate/Routing/Router.php(656): Illuminate\\Routing\\Router->dispatchToRoute()
#53 /var/www/jexactyl/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(190): Illuminate\\Routing\\Router->dispatch()
#54 /var/www/jexactyl/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#55 /var/www/jexactyl/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#56 /var/www/jexactyl/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#57 /var/www/jexactyl/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle()
#58 /var/www/jexactyl/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#59 /var/www/jexactyl/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#60 /var/www/jexactyl/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle()
#61 /var/www/jexactyl/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#62 /var/www/jexactyl/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
#63 /var/www/jexactyl/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#64 /var/www/jexactyl/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle()
#65 /var/www/jexactyl/vendor/laravel/framework/src/Illuminate/Http/Middleware/HandleCors.php(62): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#66 /var/www/jexactyl/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Http\\Middleware\\HandleCors->handle()
#67 /var/www/jexactyl/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(39): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#68 /var/www/jexactyl/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Http\\Middleware\\TrustProxies->handle()
#69 /var/www/jexactyl/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#70 /var/www/jexactyl/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(165): Illuminate\\Pipeline\\Pipeline->then()
#71 /var/www/jexactyl/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(134): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#72 /var/www/jexactyl/public/index.php(68): Illuminate\\Foundation\\Http\\Kernel->handle()
#73 {main}
"} 
[2022-10-29 07:33:24] production.ERROR: Pterodactyl\Transformers\Api\Client\ActivityLogTransformer::transform(): Argument #1 ($model) must be of type Pterodactyl\Models\ActivityLog, null given, called in /var/www/jexactyl/vendor/league/fractal/src/Scope.php on line 357 {"userId":393,"exception":"[object] (TypeError(code: 0): Pterodactyl\\Transformers\\Api\\Client\\ActivityLogTransformer::transform(): Argument #1 ($model) must be of type Pterodactyl\\Models\\ActivityLog, null given, called in /var/www/jexactyl/vendor/league/fractal/src/Scope.php on line 357 at /var/www/jexactyl/app/Transformers/Api/Client/ActivityLogTransformer.php:19)
[stacktrace]
#0 /var/www/jexactyl/vendor/league/fractal/src/Scope.php(357): Pterodactyl\\Transformers\\Api\\Client\\ActivityLogTransformer->transform()
#1 /var/www/jexactyl/vendor/league/fractal/src/Scope.php(292): League\\Fractal\\Scope->fireTransformer()
#2 /var/www/jexactyl/vendor/league/fractal/src/Scope.php(173): League\\Fractal\\Scope->executeResourceTransformers()
#3 /var/www/jexactyl/vendor/spatie/fractalistic/src/Fractal.php(369): League\\Fractal\\Scope->toArray()
#4 /var/www/jexactyl/app/Http/Controllers/Api/Client/ActivityLogController.php(43): Spatie\\Fractalistic\\Fractal->toArray()
#5 /var/www/jexactyl/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): Pterodactyl\\Http\\Controllers\\Api\\Client\\ActivityLogController->latest()
#6 /var/www/jexactyl/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(43): Illuminate\\Routing\\Controller->callAction()
#7 /var/www/jexactyl/vendor/laravel/framework/src/Illuminate/Routing/Route.php(260): Illuminate\\Routing\\ControllerDispatcher->dispatch()
#8 /var/www/jexactyl/vendor/laravel/framework/src/Illuminate/Routing/Route.php(205): Illuminate\\Routing\\Route->runController()
#9 /var/www/jexactyl/vendor/laravel/framework/src/Illuminate/Routing/Router.php(725): Illuminate\\Routing\\Route->run()
#10 /var/www/jexactyl/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#11 /var/www/jexactyl/app/Http/Middleware/Activity/AccountSubject.php(20): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#12 /var/www/jexactyl/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Pterodactyl\\Http\\Middleware\\Activity\\AccountSubject->handle()
#13 /var/www/jexactyl/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php(126): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#14 /var/www/jexactyl/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php(102): Illuminate\\Routing\\Middleware\\ThrottleRequests->handleRequest()
#15 /var/www/jexactyl/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php(54): Illuminate\\Routing\\Middleware\\ThrottleRequests->handleRequestUsingNamedLimiter()
#16 /var/www/jexactyl/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Routing\\Middleware\\ThrottleRequests->handle()
#17 /var/www/jexactyl/app/Http/Middleware/Api/Client/RequireClientApiKey.php(23): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#18 /var/www/jexactyl/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Pterodactyl\\Http\\Middleware\\Api\\Client\\RequireClientApiKey->handle()
#19 /var/www/jexactyl/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#20 /var/www/jexactyl/app/Http/Middleware/Api/Client/SubstituteClientBindings.php(32): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle()
#21 /var/www/jexactyl/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Pterodactyl\\Http\\Middleware\\Api\\Client\\SubstituteClientBindings->handle()
#22 /var/www/jexactyl/app/Http/Middleware/Api/AuthenticateIPAccess.php(31): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#23 /var/www/jexactyl/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Pterodactyl\\Http\\Middleware\\Api\\AuthenticateIPAccess->handle()
#24 /var/www/jexactyl/app/Http/Middleware/RequireTwoFactorAuthentication.php(54): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#25 /var/www/jexactyl/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Pterodactyl\\Http\\Middleware\\RequireTwoFactorAuthentication->handle()
#26 /var/www/jexactyl/app/Http/Middleware/Activity/TrackAPIKey.php(26): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#27 /var/www/jexactyl/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Pterodactyl\\Http\\Middleware\\Activity\\TrackAPIKey->handle()
#28 /var/www/jexactyl/app/Http/Middleware/Api/IsValidJson.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#29 /var/www/jexactyl/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Pterodactyl\\Http\\Middleware\\Api\\IsValidJson->handle()
#30 /var/www/jexactyl/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php(44): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#31 /var/www/jexactyl/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Auth\\Middleware\\Authenticate->handle()
#32 /var/www/jexactyl/vendor/laravel/sanctum/src/Http/Middleware/EnsureFrontendRequestsAreStateful.php(33): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#33 /var/www/jexactyl/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Laravel\\Sanctum\\Http\\Middleware\\EnsureFrontendRequestsAreStateful->Laravel\\Sanctum\\Http\\Middleware\\{closure}()
#34 /var/www/jexactyl/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#35 /var/www/jexactyl/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle()
#36 /var/www/jexactyl/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#37 /var/www/jexactyl/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest()
#38 /var/www/jexactyl/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Session\\Middleware\\StartSession->handle()
#39 /var/www/jexactyl/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#40 /var/www/jexactyl/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle()
#41 /var/www/jexactyl/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#42 /var/www/jexactyl/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle()
#43 /var/www/jexactyl/vendor/laravel/sanctum/src/Http/Middleware/EnsureFrontendRequestsAreStateful.php(26): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#44 /var/www/jexactyl/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(162): Laravel\\Sanctum\\Http\\Middleware\\EnsureFrontendRequestsAreStateful->Laravel\\Sanctum\\Http\\Middleware\\{closure}()
#45 /var/www/jexactyl/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#46 /var/www/jexactyl/vendor/laravel/sanctum/src/Http/Middleware/EnsureFrontendRequestsAreStateful.php(34): Illuminate\\Pipeline\\Pipeline->then()
#47 /var/www/jexactyl/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Laravel\\Sanctum\\Http\\Middleware\\EnsureFrontendRequestsAreStateful->handle()
#48 /var/www/jexactyl/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#49 /var/www/jexactyl/vendor/laravel/framework/src/Illuminate/Routing/Router.php(726): Illuminate\\Pipeline\\Pipeline->then()
#50 /var/www/jexactyl/vendor/laravel/framework/src/Illuminate/Routing/Router.php(703): Illuminate\\Routing\\Router->runRouteWithinStack()
#51 /var/www/jexactyl/vendor/laravel/framework/src/Illuminate/Routing/Router.php(667): Illuminate\\Routing\\Router->runRoute()
#52 /var/www/jexactyl/vendor/laravel/framework/src/Illuminate/Routing/Router.php(656): Illuminate\\Routing\\Router->dispatchToRoute()
#53 /var/www/jexactyl/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(190): Illuminate\\Routing\\Router->dispatch()
#54 /var/www/jexactyl/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#55 /var/www/jexactyl/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#56 /var/www/jexactyl/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#57 /var/www/jexactyl/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle()
#58 /var/www/jexactyl/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#59 /var/www/jexactyl/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#60 /var/www/jexactyl/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle()
#61 /var/www/jexactyl/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#62 /var/www/jexactyl/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
#63 /var/www/jexactyl/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#64 /var/www/jexactyl/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle()
#65 /var/www/jexactyl/vendor/laravel/framework/src/Illuminate/Http/Middleware/HandleCors.php(62): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#66 /var/www/jexactyl/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Http\\Middleware\\HandleCors->handle()
#67 /var/www/jexactyl/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(39): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#68 /var/www/jexactyl/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Http\\Middleware\\TrustProxies->handle()
#69 /var/www/jexactyl/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#70 /var/www/jexactyl/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(165): Illuminate\\Pipeline\\Pipeline->then()
#71 /var/www/jexactyl/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(134): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#72 /var/www/jexactyl/public/index.php(68): Illuminate\\Foundation\\Http\\Kernel->handle()
#73 {main}
"}
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by OlekAleksander** [comment]
@cmrxnn  Will you try to fix it for the next release?
I need it fixed asap.

**Comment by camwhi-te** [comment]
Logs are not relevant therefore I am unable to confirm this issue

**Comment by camwhi-te** [comment]
Just did my own testing, can confirm this is an issue, marking as a bug

**Comment by OlekAleksander** [comment]
> Logs are not relevant therefore I am unable to confirm this issue

Yeah, that's what I was thinking too. But I posted them anyway.

**Comment by DarkShoro** [comment]
Seems to be some sort of check failing to return true

`[2022-11-01 21:24:50] production.ERROR: Declaration of Pterodactyl\Http\Requests\Admin\UserFormRequest::rules() must be compatible with Pterodactyl\Http\Requests\Admin\AdminFormRequest::rules(): array {"userId":10,"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Declaration of Pterodactyl\\Http\\Requests\\Admin\\UserFormRequest::rules() must be compatible with Pterodactyl\\Http\\Requests\\Admin\\AdminFormRequest::rules(): array at /var/www/vhosts/axomunity.fr/dockers.axomunity.fr/app/Http/Requests/Admin/UserFormRequest.php:14)
[stacktrace]
#0 {main}
"} `
