### ISSUE TITLE
Still 500 error on everest beta2 on register and now login

### ISSUE THREAD

**Issue by GamingBaeren** [Jexactyl/Jexactyl#369]
### Current Behavior

When I register or login i get error 500 log below

### Expected Behavior

Tjat it works 

### Steps to Reproduce

Updatet from beta1 to beta2 
Added discord auth keys 
Tryed to login/register in inkognito tab to prevent cookie erros but error 500

### Panel Version

4.0.0beta2

### Wings Version

1.11.11

### Error Logs

```bash
[2024-12-27 14:51:27] production.ERROR: Too few arguments to function Everest\Http\Controllers\Auth\AbstractLoginController::__construct(), 0 passed in /var/www/jexactyl/app/Http/Controllers/Auth/LoginController.php on line 27 and exactly 1 expected {"exception":"[object] (ArgumentCountError(code: 0): Too few arguments to function Everest\\Http\\Controllers\\Auth\\AbstractLoginController::__construct(), 0 passed in /var/www/jexactyl/app/Http/Controllers/Auth/LoginController.php on line 27 and exactly 1 expected at /var/www/jexactyl/app/Http/Controllers/Auth/AbstractLoginController.php:45)
[stacktrace]
#0 /var/www/jexactyl/app/Http/Controllers/Auth/LoginController.php(27): Everest\\Http\\Controllers\\Auth\\AbstractLoginController->__construct()
#1 [internal function]: Everest\\Http\\Controllers\\Auth\\LoginController->__construct()
#2 /var/www/jexactyl/vendor/laravel/framework/src/Illuminate/Container/Container.php(929): ReflectionClass->newInstanceArgs()
#3 /var/www/jexactyl/vendor/laravel/framework/src/Illuminate/Container/Container.php(770): Illuminate\\Container\\Container->build()
#4 /var/www/jexactyl/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(935): Illuminate\\Container\\Container->resolve()
#5 /var/www/jexactyl/vendor/laravel/framework/src/Illuminate/Container/Container.php(706): Illuminate\\Foundation\\Application->resolve()
#6 /var/www/jexactyl/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(920): Illuminate\\Container\\Container->make()
#7 /var/www/jexactyl/vendor/laravel/framework/src/Illuminate/Routing/Route.php(274): Illuminate\\Foundation\\Application->make()
#8 /var/www/jexactyl/vendor/laravel/framework/src/Illuminate/Routing/Route.php(1100): Illuminate\\Routing\\Route->getController()
#9 /var/www/jexactyl/vendor/laravel/framework/src/Illuminate/Routing/Route.php(1031): Illuminate\\Routing\\Route->controllerMiddleware()
#10 /var/www/jexactyl/vendor/laravel/framework/src/Illuminate/Routing/Router.php(810): Illuminate\\Routing\\Route->gatherMiddleware()
#11 /var/www/jexactyl/vendor/laravel/framework/src/Illuminate/Routing/Router.php(792): Illuminate\\Routing\\Router->gatherRouteMiddleware()
#12 /var/www/jexactyl/vendor/laravel/framework/src/Illuminate/Routing/Router.php(776): Illuminate\\Routing\\Router->runRouteWithinStack()
#13 /var/www/jexactyl/vendor/laravel/framework/src/Illuminate/Routing/Router.php(740): Illuminate\\Routing\\Router->runRoute()
#14 /var/www/jexactyl/vendor/laravel/framework/src/Illuminate/Routing/Router.php(729): Illuminate\\Routing\\Router->dispatchToRoute()
#15 /var/www/jexactyl/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(200): Illuminate\\Routing\\Router->dispatch()
#16 /var/www/jexactyl/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#17 /var/www/jexactyl/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#18 /var/www/jexactyl/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#19 /var/www/jexactyl/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle()
#20 /var/www/jexactyl/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#21 /var/www/jexactyl/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#22 /var/www/jexactyl/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle()
#23 /var/www/jexactyl/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#24 /var/www/jexactyl/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
#25 /var/www/jexactyl/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#26 /var/www/jexactyl/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle()
#27 /var/www/jexactyl/vendor/laravel/framework/src/Illuminate/Http/Middleware/HandleCors.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#28 /var/www/jexactyl/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Http\\Middleware\\HandleCors->handle()
#29 /var/www/jexactyl/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(39): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#30 /var/www/jexactyl/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Http\\Middleware\\TrustProxies->handle()
#31 /var/www/jexactyl/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#32 /var/www/jexactyl/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(175): Illuminate\\Pipeline\\Pipeline->then()
#33 /var/www/jexactyl/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(144): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#34 /var/www/jexactyl/public/index.php(67): Illuminate\\Foundation\\Http\\Kernel->handle()
#35 {main}
"}
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by GamingBaeren** [comment]
Hope the problem is on my side XD

**Comment by TheGamer3514** [comment]
This got patched in a recent pr, hasn't been pushed to a beta release though

**Comment by TheGamer3514** [comment]
#367

**Comment by GamingBaeren** [comment]
Ok thought it stand in tje release from beta2 that it's fixed the error
